/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Story as PrismaStory,
  Category as PrismaCategory,
  AgeGroup as PrismaAgeGroup,
  Genre as PrismaGenre,
} from "@prisma/client";

import { StoryCreateInput } from "./StoryCreateInput";
import { Story } from "./Story";

export class StoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.StoryCountArgs, "select">): Promise<number> {
    return this.prisma.story.count(args);
  }

  async stories(args: Prisma.StoryFindManyArgs): Promise<PrismaStory[]> {
    return this.prisma.story.findMany(args);
  }
  async story(args: Prisma.StoryFindUniqueArgs): Promise<PrismaStory | null> {
    return this.prisma.story.findUnique(args);
  }
  async createStory(args: Prisma.StoryCreateArgs): Promise<PrismaStory> {
    return this.prisma.story.create(args);
  }
  async updateStory(args: Prisma.StoryUpdateArgs): Promise<PrismaStory> {
    return this.prisma.story.update(args);
  }
  async deleteStory(args: Prisma.StoryDeleteArgs): Promise<PrismaStory> {
    return this.prisma.story.delete(args);
  }

  async getCategory(parentId: string): Promise<PrismaCategory | null> {
    return this.prisma.story
      .findUnique({
        where: { id: parentId },
      })
      .category();
  }

  async getAgeGroup(parentId: string): Promise<PrismaAgeGroup | null> {
    return this.prisma.story
      .findUnique({
        where: { id: parentId },
      })
      .ageGroup();
  }

  async getGenre(parentId: string): Promise<PrismaGenre | null> {
    return this.prisma.story
      .findUnique({
        where: { id: parentId },
      })
      .genre();
  }
  async GenerateStory(args: StoryCreateInput): Promise<Story> {
    throw new Error("Not implemented");
  }
}
