/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { AgeGroupWhereUniqueInput } from "../../ageGroup/base/AgeGroupWhereUniqueInput";
import { GenreWhereUniqueInput } from "../../genre/base/GenreWhereUniqueInput";

@InputType()
class StoryWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  image?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AgeGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AgeGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => AgeGroupWhereUniqueInput, {
    nullable: true,
  })
  ageGroup?: AgeGroupWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => GenreWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GenreWhereUniqueInput)
  @IsOptional()
  @Field(() => GenreWhereUniqueInput, {
    nullable: true,
  })
  genre?: GenreWhereUniqueInput;
}

export { StoryWhereInput as StoryWhereInput };
