/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { AgeGroupWhereUniqueInput } from "../../ageGroup/base/AgeGroupWhereUniqueInput";
import { GenreWhereUniqueInput } from "../../genre/base/GenreWhereUniqueInput";

@InputType()
class StoryUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  image?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AgeGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AgeGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => AgeGroupWhereUniqueInput, {
    nullable: true,
  })
  ageGroup?: AgeGroupWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => GenreWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GenreWhereUniqueInput)
  @IsOptional()
  @Field(() => GenreWhereUniqueInput, {
    nullable: true,
  })
  genre?: GenreWhereUniqueInput | null;
}

export { StoryUpdateInput as StoryUpdateInput };
