/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AgeGroupService } from "../ageGroup.service";
import { AgeGroupCreateInput } from "./AgeGroupCreateInput";
import { AgeGroup } from "./AgeGroup";
import { AgeGroupFindManyArgs } from "./AgeGroupFindManyArgs";
import { AgeGroupWhereUniqueInput } from "./AgeGroupWhereUniqueInput";
import { AgeGroupUpdateInput } from "./AgeGroupUpdateInput";
import { StoryFindManyArgs } from "../../story/base/StoryFindManyArgs";
import { Story } from "../../story/base/Story";
import { StoryWhereUniqueInput } from "../../story/base/StoryWhereUniqueInput";

export class AgeGroupControllerBase {
  constructor(protected readonly service: AgeGroupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AgeGroup })
  async createAgeGroup(
    @common.Body() data: AgeGroupCreateInput
  ): Promise<AgeGroup> {
    return await this.service.createAgeGroup({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AgeGroup] })
  @ApiNestedQuery(AgeGroupFindManyArgs)
  async ageGroups(@common.Req() request: Request): Promise<AgeGroup[]> {
    const args = plainToClass(AgeGroupFindManyArgs, request.query);
    return this.service.ageGroups({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AgeGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ageGroup(
    @common.Param() params: AgeGroupWhereUniqueInput
  ): Promise<AgeGroup | null> {
    const result = await this.service.ageGroup({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AgeGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAgeGroup(
    @common.Param() params: AgeGroupWhereUniqueInput,
    @common.Body() data: AgeGroupUpdateInput
  ): Promise<AgeGroup | null> {
    try {
      return await this.service.updateAgeGroup({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AgeGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAgeGroup(
    @common.Param() params: AgeGroupWhereUniqueInput
  ): Promise<AgeGroup | null> {
    try {
      return await this.service.deleteAgeGroup({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/stories")
  @ApiNestedQuery(StoryFindManyArgs)
  async findStories(
    @common.Req() request: Request,
    @common.Param() params: AgeGroupWhereUniqueInput
  ): Promise<Story[]> {
    const query = plainToClass(StoryFindManyArgs, request.query);
    const results = await this.service.findStories(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        content: true,
        image: true,

        category: {
          select: {
            id: true,
          },
        },

        ageGroup: {
          select: {
            id: true,
          },
        },

        genre: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stories")
  async connectStories(
    @common.Param() params: AgeGroupWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        connect: body,
      },
    };
    await this.service.updateAgeGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stories")
  async updateStories(
    @common.Param() params: AgeGroupWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        set: body,
      },
    };
    await this.service.updateAgeGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stories")
  async disconnectStories(
    @common.Param() params: AgeGroupWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        disconnect: body,
      },
    };
    await this.service.updateAgeGroup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
